### ISSUE TITLE
Prevents backspacing within a Google Docs Spreadsheet

### ISSUE THREAD

**Issue by skladek** [cranman/BackStop#1]
Issue:
- When using backspace, I am unable to backspace to delete characters while editing a cell within any google docs spreadsheet. A URL blacklist would be excellent to allow docs.google.com to be blacklisted while retaining the backstop functionality elsewhere.

**Comment by cranman** [comment]
Thanks for raising this issue.

I'm not entirely sure as to why BackStop was disabling character deletion in Google Docs, but I've disabled BackStop from working on Google Docs and pushed the update to the Chrome Extension Gallery. It should update when your Chrome checks for updates to extensions.

Let me know if you have any more problems.
